site_name: API Gears
site_description: lean cycle to discover APIs and drive the product cycle
site_author: XPixels
copyright: 2019 XPixels GmbH
dev_addr: 0.0.0.0:8080

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "indigo"
  font:
    text: "Segoe UI"
    code: "Segoe Mono"
  logo:
    icon: "home"
  language: "en"
  extra:
    search:
      language: "en"
  feature:
    tabs: true

nav:
  - Guide:
      - "Introduction": "guide/intro.md"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.magiclink
